# Generated by Django 2.0.5 on 2019-03-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
            ],
        ),
    ]
